### ISSUE TITLE
what do u mean with Input URL

### ISSUE THREAD

**Issue by nedz14** [mansimarkaur/webpage-scraper#2]
Open http://127.0.0.1:5000/ in your browser. Input URL and have fun.
what do u mean with Input URL.
what url and where to input it?

**Comment by nedz14** [comment]
i trired this and here is the outout:
F:\Programs\PortableGit\webpage-scraper>python crawler_flask.py https://myanimel
ist.net/anime/658/Touhai_Densetsu_Akagi__Yami_ni_Maiorita_Tensai/userrecs
  File "crawler_flask.py", line 23
    print url
            ^
SyntaxError: invalid syntax

F:\Programs\PortableGit\webpage-scraper>

**Comment by mansimarkaur** [comment]
The URL doesn't have to be given through command line arguments.  After you run the `crawler_flask.py` using the command `python crawler_flask.py`, open your browser and go to http://127.0.0.1:5000/ . You'll see an input field in which you have to input the URL of the webpage you want to scrape and select the desired options from fetching all the hyperlinks in that page, or fetching all the images on that page, or the HTML source code or the text of the page.

**Comment by nedz14** [comment]
same result :(
F:\Programs\PortableGit\webpage-scraper>python crawler_flask.py
  File "crawler_flask.py", line 23
    print url
            ^
SyntaxError: invalid syntax

F:\Programs\PortableGit\webpage-scraper>

i get (Page load error) when openning http://127.0.0.1:5000/ in browser.

**Comment by mansimarkaur** [comment]
@nedz14 Do you get `* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)` or a similar message after you run the command `python crawler_flask.py`? If not, please check if have localhost setup correctly on your system.
